---
- hosts: tomcat
  become: true
  roles:
  - install-pre

- hosts: tomcat
  become: true
  become_user: tomcat
  roles:
  - install_tomcat

- hosts: tomcat
  become: true
  roles:
  - install-post

- hosts: tomcat
  become: true
  become_user: tomcat
  roles:
  - install-webapp

- hosts: tomcat
  become: true
  roles:
  - startwebapp

