---
- name: "extract employees"
  copy: 
    src: employees 
    dest: /home/tomcat
    owner: tomcat
    group: tomcat
    mode: 0755

- name: "copy employees.war"
  copy: 
    src: /home/tomcat/employees/data/webapp/employees.war 
    dest: /opt/tomcat/latest/webapps 
    owner: tomcat 
    group: tomcat 
    mode: 0755
    remote_src: yes

- name: "copy DB Properties"
  copy:
    src: /home/tomcat/employees/data/conf/db.properties
    dest: /home/tomcat
    owner: tomcat
    group: tomcat
    mode: 0755
    remote_src: yes

- name: "copy DB Treiber"
  copy:
    src: /home/tomcat/employees/data/lib/db_driver/
    dest: "/opt/tomcat/libs/{{JAVA_VERSION}}/lib/"
    owner: tomcat
    group: tomcat
    mode: 0755
    remote_src: yes
